# Generated by Django 5.2.8 on 2025-12-23 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('item_type', models.CharField(choices=[('RM', 'Raw Material'), ('FG', 'Finished Good')], default='RM', max_length=2)),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('avg_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('sack_size', models.JSONField(blank=True, null=True)),
                ('usage_type', models.CharField(blank=True, choices=[('Blending', 'Blending'), ('Packing', 'Packing')], max_length=20, null=True)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='used_in', to='inventory.itemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.DecimalField(decimal_places=3, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=10)),
                ('rm_usage_snapshot', models.JSONField(blank=True, help_text='Snapshot of RMs used and their quantities', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_good', models.ForeignKey(limit_choices_to={'item_type': 'FG'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('IN', 'Inward'), ('OUT', 'Outward'), ('ADJ', 'Adjustment')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.itemmaster')),
            ],
        ),
    ]
