# Generated by Django 5.2.8 on 2025-12-23 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmaster',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of RM per 1 unit of FG', max_digits=12)),
                ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='inventory.itemmaster')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_bom', to='inventory.itemmaster')),
            ],
        ),
    ]
